modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="ender_additions"
version="1.0.0"
displayName="Ender Additions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="zaze_gaming, MCreator"

[[dependencies.ender_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



